language: node_js
services:
  - docker

script:
  - npm install

after_success:
  - pip install --user awscli
  - eval $(aws ecr get-login --region us-east-2 --no-include-email)
  - docker build -t isentest .
  - docker tag isentest 503259967594.dkr.ecr.us-east-2.amazonaws.com/isentestaws
  - docker push 503259967594.dkr.ecr.us-east-2.amazonaws.com/isentestaws

